Models/Producto.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace POS.Models;
[BindProperties]
public partial class Producto
{
    public int ProductoId { get; set; }
   
  
    //[StringLength(13, ErrorMessage = "El código de barra debe tener exactamente 13 caracteres.", MinimumLength = 13)]
    [RegularExpression("^[0-9]+$", ErrorMessage = "El código de barra debe contener solo números.")]
    public string CodigoBarra { get; set; } = null!;
  
    public string Nombre { get; set; } = null!;
    [Display(Name ="Peso Neto")]
    public int PesoNeto { get; set; }
   // [Display(Name = "Categoria")]
    public int? CategoriaId { get; set; }

    //HAY QUE REALIZAR EL CAMBIO EN EL CONTROLADOR DE EDICION DE PRODUCTO
    //SE DEBE REMOVER LA PROPEIDAD DE MODELO "CATEGORIA" DE LA VALIDACION DE MODELOS QUE SE GENERA EN EL CONTROLADOR 
    //(!MODELSTATE.ISVALID) => REMOVE(CATEGORIA) --> RESUELTO
   
    public virtual Categoria? Categoria { get; set; }

    public virtual ControlPrecio? ControlPrecio { get; set; }

    public virtual ICollection<DetalleVenta> DetalleVenta { get; set; } = new List<DetalleVenta>();

    public  virtual Stock? Stock { get; set; }
}

Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;
using POS.Models;

namespace POS.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categoria.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.CategoriaId == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoriaId,Descripcion")] Categoria categoria)
        {
            
                if (ModelState.IsValid)
                {
                using (var transaction = await _context.Database.BeginTransactionAsync())
                {
                    try
                    {
                        _context.Add(categoria);
                        await _context.SaveChangesAsync();

                        await transaction.CommitAsync();

                        TempData["ExitoMessage"] = "Categoria Ingresada Correctamente";

                        return RedirectToAction(nameof(Index));
                    }
                    catch(Exception ex)
                    {
                        await transaction.RollbackAsync();
                        ModelState.AddModelError("","Ocurrio un Error");
                        Console.WriteLine(ex.Message);
                    }
                }
                    
                }
            
           
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoriaId,Descripcion")] Categoria categoria)
        {
            if (id != categoria.CategoriaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.CategoriaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria.
                Include(c => c.Productos)
                .FirstOrDefaultAsync(m => m.CategoriaId == id);
            if (categoria == null)
            {
                return NotFound();
            }
            if (categoria.Productos != null && categoria.Productos.Any())
            {
                throw new InvalidOperationException("No se peude eliminar esta categoria porque esta vinculada a un producto");
            }
            else
            {
                return View(categoria);
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria != null)
            {
                _context.Categoria.Remove(categoria);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(int id)
        {
            return _context.Categoria.Any(e => e.CategoriaId == id);
        }
    }
}

Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;
using POS.Models;

namespace POS.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        //// GET: Productos
        //public async Task<IActionResult> Index()
        //{
        //    var applicationDbContext = _context.Productos.Include(p => p.Categoria);
        //    return View(await applicationDbContext.ToListAsync());
        //}

        //Filtro de BUSQUEDAS PARA LOS PRODUCTOS POR CONSULTAS DE CODIGOBARRA, CATEGORIA Y NOMBRE
        public async Task<IActionResult> Index(string BuscarNombre, string BuscarCategoria, string BuscarCodigoBarra)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity Set 'ApplicationDbContext.Productos' is null");
            }

            var productos = (from p in _context.Productos.Include(p => p.Categoria)
                             where (String.IsNullOrEmpty(BuscarCategoria) || p.Categoria.Descripcion.ToUpper().Contains(BuscarCategoria.ToUpper()))
                             && (String.IsNullOrEmpty(BuscarCodigoBarra) || p.CodigoBarra.ToUpper().Contains(BuscarCodigoBarra.ToUpper()))
                             && (String.IsNullOrEmpty(BuscarNombre) || p.Nombre.ToUpper().Contains(BuscarNombre.ToUpper()))
                             select p).ToListAsync();

            return View(await productos);
        }


        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }



        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("ProductoId,CodigoBarra,Nombre,PesoNeto,CategoriaId")] Producto producto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(producto);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Descripcion", producto.CategoriaId);
        //    return View(producto);
        //}

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Descripcion");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductoViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _context.Database.BeginTransactionAsync())
                {
                    try
                    {
                        //Agrega datos de producto a la BD
                        var producto = new Producto
                        {
                            CodigoBarra = model.CodigoBarra,
                            Nombre = model.Nombre,
                            PesoNeto = (int)model.PesoNeto,
                            CategoriaId = model.CategoriaId

                        };
                        _context.Add(producto);
                        await _context.SaveChangesAsync();

                        //Id de producto
                        model.ProductoId = producto.ProductoId;

                        //Agrega datos de ControlPrecio al DB
                        var controlPrecio = new ControlPrecio
                        {
                            ProductoId = model.ProductoId,
                            Costo = model.Costo,
                            PorcentajeGanancia = model.PorcentajeGanancia,
                            PrecioVenta = (decimal)(model.Costo + ((model.Costo * model.PorcentajeGanancia) / 100)),
                            CodigoBarra = model.CodigoBarra
                        };
                        _context.Add(controlPrecio);
                        await _context.SaveChangesAsync();

                        //Agrega datos de Stock al DB
                        var stock = new Stock
                        {
                            ProductoId = model.ProductoId,
                            Cantidad = model.Cantidad,
                            CodigoBarra = model.CodigoBarra
                        };
                        _context.Add(stock);
                        await _context.SaveChangesAsync();

                        await transaction.CommitAsync();

                        return RedirectToAction("Index");

                    }
                    catch (Exception ex)
                    {
                        await transaction.RollbackAsync();
                        ModelState.AddModelError("", "Ocurrio un Error");
                        Console.WriteLine(ex.Message);
                    }
                }
            }
            //foreach (var modelError in ModelState.Values.SelectMany(v => v.Errors))
            //{
            //    Console.WriteLine(modelError.ErrorMessage);
            //}
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Descripcion");
            return View(model);
        }



        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(p => p.ProductoId == id);


            if (producto == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Descripcion", producto.CategoriaId);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoId,CodigoBarra,Nombre,PesoNeto,CategoriaId")] Producto producto)
        {
            if (id != producto.ProductoId)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                //ModelState.Remove("CategoriaId");
                var errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
                // Inspecciona 'errors' para ver qué campos están fallando
            }
            //Hubo un problema en la validacion de las propiedades Bind con las propiedades de la clase Producto, el controlador intentaba validar 
            //dos veces categorias, CategoriaId y Categoria, esta ultima ASP.NET MVC la trataba como una mas
            //de las propiedades a validar por ser Virutal

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }


            //foreach (var modelError in ModelState.Values.SelectMany(v => v.Errors))
            //{
            //    Console.WriteLine(modelError.ErrorMessage);
            //}


            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Descripcion", producto.CategoriaId);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound(); //NOTFOUND
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // SE ESTABAN GENERANDO LOS CAMBIOS PARA ELIMINAR LAS ENTIDADES RELACIONADAS AL PRODUCTO

            //ACA SE INCLUYEN LAS ENTIDADES Y LUEGO SE DEBEN ELIMINAR LOS REGISTROS RELACIONADOS 
            var producto = await _context.Productos //Con metodos de seleccion se busca en la base de datos(_context) la relacion del producto con stock y controlPrecio
                .Include(p => p.Stock)
                .Include(p => p.ControlPrecio)

Views/Productos/Create.cshtml
@model POS.Models.ProductoViewModel

@{
    ViewData["Title"] = "Crear Producto";
}

<h2>Crear Producto</h2>

<form asp-action="Create" method="post" class="w-50">
    <div class="form-group">
        <label asp-for="CodigoBarra" class="control-label"></label>
        <input asp-for="CodigoBarra" class="form-control" />
        <span asp-validation-for="CodigoBarra" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PesoNeto" class="control-label"></label>
        <input type="text" asp-for="PesoNeto" class="form-control" />
        <span asp-validation-for="PesoNeto" class="text-danger"></span>
    </div>

     <div class="form-group mb-2">
        <label asp-for="CategoriaId" class="control-label"></label>
        <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select> 
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>

    <a asp-controller="Categorias" asp-action="Create" class="btn btn-secondary mb-2">Ir a Crear Categoria</a>

    <hr />
    <h4>Datos para Control de Precio</h4>

    <div class="form-group">
        <label asp-for="Costo" class="control-label"></label>
        <input id="Costo" value="0.0" type="number" asp-for="Costo" class="form-control" />
        <span asp-validation-for="Costo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PorcentajeGanancia" class="control-label"></label>
        <input id="PorcentajeGanancia" value="0.0" type="number" asp-for="PorcentajeGanancia" class="form-control" />
        <span asp-validation-for="PorcentajeGanancia" class="text-danger"></span>
    </div>

    <hr />
    <h4>Datos de Stock</h4>

    <div class="form-group">
        <label asp-for="Cantidad" class="control-label"></label>
        <input id="Cantidad" value="0" type="number" asp-for="Cantidad" class="form-control" />
        <span asp-validation-for="Cantidad" class="text-danger"></span>
    </div>

    <br/>

    <button type="submit" class="btn btn-primary">Guardar</button>
    <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

@* @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} *@

<script>
    document.querySelectorAll("input[type='number']").forEach(function(input) {
        input.addEventListener("focus", function(){
            this.select();
        })
    });

    // document.getElementById("Cantidad","Costo","PorcentajeGanancia").addEventListener("focus", function(){
    //        this.select();
    //    });
</script>


@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/localization/messages_es.js"></script>

    <script>
        // Cambia el validador de número para aceptar decimales con coma
        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /^-?\d+(\,\d{1,2})?$/.test(value);
        };

       
    </script>
}

Views/Productos/Delete.cshtml
@model POS.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Producto</h1>


<div>
    <h4>Confirmar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoBarra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoBarra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PesoNeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PesoNeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger mb-2" /> 
        <a class="btn btn-outline-primary mb-2" asp-action="Index">Volver Atras</a>
    </form>
</div>

Views/Productos/Details.cshtml
@model POS.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoBarra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoBarra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PesoNeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PesoNeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info mb-2" asp-action="Edit" asp-route-id="@Model?.ProductoId">Editar</a> 
    <a class="btn btn-outline-primary mb-2" asp-action="Index">Volver Atras</a>
</div>

Views/Productos/Edit.cshtml
@model POS.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Producto:</h1>

<h4><i class="fa-brands fa-elementor"></i>@Model.Nombre @Model.PesoNeto @FuncionesProductosViews.DevolverPesoSegunCategoria(Model.Categoria.Descripcion)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductoId" />
            <div class="form-group">
                <label asp-for="CodigoBarra" class="control-label"></label>
                <input asp-for="CodigoBarra" class="form-control" />
                <span asp-validation-for="CodigoBarra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PesoNeto" class="control-label">Peso Neto (@FuncionesProductosViews.DevolverPesoSegunCategoria(Model.Categoria.Descripcion))</label>
                <input asp-for="PesoNeto" class="form-control" />
                <span asp-validation-for="PesoNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select>
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a style="text-decoration:none" class="btn btn-outline-primary" asp-action="Index">Volver Atras</a>
            </div>
        </form>
    </div>
</div>



 @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} 

Views/Productos/Index.cshtml
@model IEnumerable<POS.Models.Producto>

@{
    ViewData["Title"] = "Productos";
}

<h1>Buscar Producto:</h1>

<form asp-action="Index" method="get">
    <div class="form-group w-25">
        <strong><label for="searchCategory">Categoría</label></strong>
        <input type="text" class="form-control" id="BuscarCategoria" name="BuscarCategoria" value="@Context.Request.Query["BuscarCategoria"]" placeholder="Nombre de la Categoría" />
    </div>

    <div class="form-group w-25">
        <strong><label for="searchBarcode">Código de Barras</label></strong>
        <input type="text" class="form-control" id="BuscarCodigoBarra" name="BuscarCodigoBarra" value="@Context.Request.Query["BuscarCodigoBarra"]" placeholder="Código de Barras" />
    </div>

    <div class="form-group w-25">
        <strong><label for="searchName">Nombre del Producto</label></strong>
        <input type="text" class="form-control" id="BuscarNombre" name="BuscarNombre" value="@Context.Request.Query["BuscarNombre"]" placeholder="Nombre del Producto" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Buscar</button>
    <button class="btn btn-outline-primary" onclick="Restaurar()">Limpiar formulario</button>
</form>

<hr/>

@{
    Html.RenderPartialAsync("_listaIndexProductos", Model);
}



<script>
    function Restaurar(){
       document.querySelector("#BuscarCategoria").value = '';
       document.querySelector("#BuscarCodigoBarra").value = '';
       document.querySelector("#BuscarNombre").value = '';
    }
</script>

Views/Productos/_listaIndexProductos.cshtml
@model IEnumerable<POS.Models.Producto>



<h2>Listado de Productos</h2>

<p>
    <a class="btn btn-outline-primary" style="text-decoration:none" asp-action="Create">Ingresar Nuevo Producto</a>
</p>
<table class="table table-striped table-bordered border-primary">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodigoBarra)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.PesoNeto)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int index = 0;
        }
        @foreach (var item in Model)
        {
            @* var par = index % 2 == 0;
            var impar = !par; *@
            @* <tr class="@(par ? "table-primary" : "table-secondary")"> *@
                <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CodigoBarra)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td style="text-align: center">
                    @Html.DisplayFor(modelItem => item.PesoNeto)
                    @FuncionesProductosViews.DevolverPesoSegunCategoria(item.Categoria.Descripcion)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Categoria.Descripcion)
                </td>
                <td class=" text-lg-end">
                    <a class="btn btn-info mb-2" style="text-decoration:none" asp-action="Edit" asp-route-id="@item.ProductoId">Editar</a> 
                    <a class="btn btn-success mb-2" style="text-decoration:none" asp-action="Details" asp-route-id="@item.ProductoId">Detalles</a> 
                    <a class="btn btn-danger mb-2" style="text-decoration:none" asp-action="Delete" asp-route-id="@item.ProductoId">Eliminar</a>
                </td>
            </tr>

            index++;
        }
    </tbody>
</table>