Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;
using POS.Models;

namespace POS.Controllers
{
    public class StocksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StocksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Stocks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Stocks
                .Include(s => s.Producto)
                .ToListAsync();
            return View(await applicationDbContext);
        }

        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .Include(s => s.Producto)
                .FirstOrDefaultAsync(m => m.StockId == id);

            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // GET: Stocks/Create
        //public IActionResult Create()
        //{
        //    ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "ProductoId");
        //    return View();
        //}

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("StockId,ProductoId,Cantidad,CodigoBarra")] Stock stock)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(stock);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "ProductoId", stock.ProductoId);
        //    return View(stock);
        //}

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .Include(s=>s.Producto)
                .FirstOrDefaultAsync(s=>s.StockId == id);


            if (stock == null)
            {
                return NotFound();
            }
            //ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "ProductoId", stock.ProductoId);
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockId,ProductoId,Cantidad,CodigoBarra")] Stock stock)
        {
            if (id != stock.StockId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.StockId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           // ViewData["ProductoId"] = new SelectList(_context.Productos, "ProductoId", "ProductoId", stock.ProductoId);
            return View(stock);
        }



        // GET: Stocks/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var stock = await _context.Stocks
        //        .Include(s => s.Producto)
        //        .FirstOrDefaultAsync(m => m.StockId == id);
        //    if (stock == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(stock);
        //}

        //// POST: Stocks/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var stock = await _context.Stocks.FindAsync(id);
        //    if (stock != null)
        //    {
        //        _context.Stocks.Remove(stock);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.StockId == id);
        }
    }
}

Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using POS.Data;
using POS.Extension;
using POS.Models;

namespace POS.Controllers
{
    public class VentasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VentasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Venta.ToListAsync());
        }


        // GET: AgregarProducto
        public ActionResult AgregarProducto()
        {
            var ListaProductos = HttpContext.Session.GetObjectFromJson<List<ListaProductoViewModel>>("ListaProductos") ?? new List<ListaProductoViewModel>();

            return View("Vender", ListaProductos);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarProducto(string codigoBarra)
        {
            // Se toman los registros de productos de la Session (un espacio de memoria temporal del servidor)
            // Este espacio de memoria temporal del servidor tiene como identificador de la sesion de usuario
            // un tipo [key,value] o tokens donde reconoce las solicitudes del cliente 
            var ListaProductos = HttpContext.Session.GetObjectFromJson<List<ListaProductoViewModel>>("ListaProductos") ?? new List<ListaProductoViewModel>();

            // Se busca un producto por el parametro codigoBarra
            var producto = await _context.Productos
                .Include(p => p.ControlPrecio)
                .Include(p => p.Stock)
                .FirstOrDefaultAsync(p => p.CodigoBarra == codigoBarra);

            
            //Se verifica que no sea nulo
            if (producto != null)
            {
                //ListaProductos es una variable que almacena el modelo de ProductoVenta(Un view model, NO es de La BD)
                //productoExiste busca el primer producto de la sesion temporal que concioda con el codigo de barra ingresado como 
                // parametro de valor de la funcion AgregarProducto

                //Se recupera un producto de una lista en caso de que haya sido ingresado con anterioridad
                var productoExiste = ListaProductos.FirstOrDefault(p => p.CodigoBarra == codigoBarra);

                //    CODIGO DE PRUEBA ELIMINAR!!
                //var stockCantidad = stockProducto.Cantidad;
                
                //Si se agrego con anterioridad se procede a lo siguiente
                if (productoExiste != null)
                {
                    // !!  CODIGO DE PRUEBA: VERIFICAR Y VALIDAR CANTIDAD EN STOCK!!
                    //if ((stockCantidad - productoExiste.Cantidad) > 0)
                    //{
                    //    //SI EL PRODUCTO YA SE ENCUENTRA EN LA LISTA TEMPORAL, SE LE SUMA LA CANTIDAD EN 1
                    //    productoExiste.Cantidad++;
                    //    productoExiste.Subtotal = productoExiste.Cantidad * productoExiste.PrecioUnitario;
                    //}
                    //else
                    //{
                    //    return BadRequest("La cantidad excede el stock disponible");
                    //}

                    //CODIGO DE PRUEBA 2 CON METODO QUE DEVUELVE TRUE O FALSE SI LA CANTIDAD SOLICITADA ES VALIDA

                        bool validarStock = ValidarStock(productoExiste.CodigoBarra, productoExiste.Cantidad + 1);
                        if (validarStock)
                        {
                            productoExiste.Cantidad++;
                            productoExiste.Subtotal = productoExiste.Cantidad * productoExiste.PrecioUnitario;
                        }
                        else
                        {
                            TempData["StockInsuficiente"] = true; //SE PUEDE USAR TEMPDATA PARA ENVIAR INFORMACION A LA VISTA
                                                                  //Y ASI PODER ACTIVAR ALGUN EVENTO EN LA VISTA EN ESTE CASP 
                        }                                         //SI ES TRUE MUESTRA UNA VENTANA EMERGENTE DE ERROR


                    //SI EL PRODUCTO YA SE ENCUENTRA EN LA LISTA TEMPORAL, SE LE SUMA LA CANTIDAD EN 1
                    //productoExiste.Cantidad++;
                    //productoExiste.Subtotal = productoExiste.Cantidad * productoExiste.PrecioUnitario;

                }
                //Si no se agrego con anterioridad se procede a ingresarlo.
                else
                {
                    bool validarStock = ValidarStock(codigoBarra, 1);
                    if (validarStock)
                    {
                        ListaProductos.Add(new ListaProductoViewModel
                        {
                            CodigoBarra = producto.CodigoBarra,
                            Nombre = producto.Nombre,
                            PesoNeto = producto.PesoNeto,
                            PrecioUnitario = producto.ControlPrecio.PrecioVenta,
                            Cantidad = 1,
                            Subtotal = producto.ControlPrecio.PrecioVenta
                        });
                    }
                    else
                    {
                        TempData["StockInsuficiente"] = true;
                    }
                    
                  

                 

                }

                HttpContext.Session.SetObjectAsJson("ListaProductos", ListaProductos);
            }


            return View("Vender", ListaProductos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //FUNCIONES AL FINALIZAR COMPRA SON: 
        //1) RESTAR LA CANTIDAD DE LOS PRODUCTOS DE LA TABLA STOCK
        //2) EN CADA FINALIZACION DE COMPRA SE DEBEN AGREGAR LOS DETALLES DE LA VENTA
        public async Task<IActionResult> FinalizarCompra()
        {
            //Variables
            var ListaProductos = HttpContext.Session.GetObjectFromJson<List<ListaProductoViewModel>>("ListaProductos") ?? new List<ListaProductoViewModel>();
            //Variable que recupera todos los codigos de barra de la Lista de la Session producida por la venta
            var codigosBarraVenta = ListaProductos.Select(l => l.CodigoBarra).ToList();
          
            //En Caso que no exista ningun producto en la Lista de Venta
            if (ListaProductos == null || !ListaProductos.Any())
            {
                return BadRequest("No hay productos en la lista de venta");
                //return View("error", new { message = "No hay productos para finalizar la compra" });

            }
            //Caso2: Existe al menos 1 producto se procede a Registrar el Total de la Compra y La Fecha y la Hora.
            else
            {
                //PROCEDIMIENTO PARA el Modelo de VENTA -------------------------1
                var totalCompra = ListaProductos.Sum(p => p.Subtotal);

                var registrarVenta = new Venta
                {
                    FechaVenta = DateTime.Now,
                    Total = (decimal)totalCompra
                    
                };
                _context.Venta.Add(registrarVenta);
                await _context.SaveChangesAsync();

                //PROCEDIMIENTO PARA el Modelo de DetalleVenta -------------------------2

                //Condiciona, mapeando la tabla productos de la BD, cada articulo que coincida con el codigo de barra de la venta,
                //devolviendo una lista.
                var productos = await _context.Productos
                    .Where(p => codigosBarraVenta.Contains(p.CodigoBarra))
                    .ToListAsync();
               

                
                //Se crea una lista de DetalleVentas mapeando ListaProductos que es de tipo Session.
                var detalleVenta = ListaProductos
                    .Select(l =>  //select mapea cada producto de session y devuelve un objeto de 
                    {             //detellaVenta para el registro de ventas.

                        //lo que guarda 
                        var producto = productos.FirstOrDefault(p => p.CodigoBarra == l.CodigoBarra);

                        return new DetalleVenta
                        {
                            VentaId = registrarVenta.VentaId,
                            ProductoId = producto.ProductoId,
                            Cantidad = l.Cantidad,
                            PrecioUnitario = l.PrecioUnitario,
                            Subtotal = l.Subtotal,
                            CodigoBarra = l.CodigoBarra
                        };
                    }).ToList();
                    
                //SE GUARDA LA LISTA DE PRODUCTOS GENERADOS EN LA VENTA, UNA VEZ FINALIZADA, EN LA BASE DE DATOS
                //COMO DETALLEVENTA
                _context.DetalleVenta.AddRange(detalleVenta);
                await _context.SaveChangesAsync();

                //------------------CONTROLAR QUE A LA HORA DE INGRESAR NUEVA CANTIDAD EN STOCK DEL PRODUCTO----------------------------
                //-----DIGAMOS QUE SE VENDIERON 12 Y HABIA 12 EN STOCK, LUEGO SE AGREGO NUEVA CANTIDAD DE STOCK EN EL PRODUCTO VENDIDO--
                //-----PERO LA SESSION PARA EJECUTAR LA VENTA NO LO IDENTIFICA----------------------------------------------------------

                //3ER PROCEDIMIENTO OBLIGATORIO - RESTAR LA CANTIDAD VENDIDA DE CADA ARTICULO DE LA VENTA
                //                                DEL REGISTRO DEL STOCK.

                //LISTA DE CODIGOS DE BARRAS VENDIDOS
                var codigosVendidos = ListaProductos.Select(l=>l.CodigoBarra).ToList();

                //STOCKS DE LOS CODIGOS DE BARRAS VENDIDOS

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POS.styles.css" asp-append-version="true" /> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body data-bs-theme="dark">
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-toggleable-sm navbar-dark bg-dark border-bottom border-body" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POS-Punto de Venta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-evenly text-uppercase">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ControlPrecios" asp-action="Index">Control de Precios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Stocks" asp-action="Index">Stock</a>
                        </li>

                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Venta
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Ventas" asp-action="Index">Registros</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Ventas" asp-action="AgregarProducto">Vender</a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <br>
    <hr>
    

     <footer class="border-top footer text-muted">
        <div class="container">
            Punto de Venta v1.2
        </div>
    </footer> 
@*     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>



@*  <li class="nav-item btn btn-sm btn-success">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ventas" asp-action="Index">Registro de Ventas</a>
                        </li>
                        <li class="nav-item btn btn-sm btn-outline-primary">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ventas" asp-action="AgregarProducto">Vender</a>
                        </li> *@